version: 2.1

workflows:
  main:
    jobs:
      - build-and-test

jobs:
  build-and-test:   
    docker:
      - image: circleci/golang:latest
        environment:
          HUGO_VERSION: 0.109.0
    steps:
      - restore_cache:
          keys:
            # See https://circleci.com/docs/2.0/caching/
            - hugo-v2-{{ .Branch }}
            - hugo-v2-
      - checkout
      - run:
          name: Install Hugo
          command: bash ./ci-install-hugo.sh
      - run:
          name: Build / Launch server
          command: hugo server
      - save_cache:
          key: hugo-v2-{{ .Branch }}
          paths:
            - "/tmp/hugo_cache/"      



# VS Code Extension Version: 1.5.1