version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  build:   
    docker:
      - image: circleci/golang:latest
        environment:
          HUGO_VERSION: 0.109.0
    steps:
      - restore_cache:
          keys:
            # See https://circleci.com/docs/2.0/caching/
            - hugo-v2-{{ .Branch }}
            - hugo-v2-
      - checkout
      - run:
          name: Install Hugo
          command: bash ./ci-install-hugo.sh
      - run:
          name: Build site
          command: hugo
      - save_cache:
          key: hugo-v2-{{ .Branch }}
          paths:
            - "/tmp/hugo_cache/"      
      - persist_to_workspace:
          root: .
          paths:
            - public

  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: .
      - node/install-packages
      - run: 
          name: "Setup custom env variables"
          command: echo 'export NETLIFY_SITE_ID="$NETLIFY_SITE_ID"' >> $BASH_ENV
      - run:
          name: Deploy to Netlify
          command: netlify deploy --dir=public --prod --message="Deployed from CircleCI"

workflows:
  main:
    jobs:
      - build
      - deploy

# VS Code Extension Version: 1.5.1